// import NavBar from "@/components/Navbar";
import "./globals.css";

import { GeneralRegular } from "@/utils/fonts";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "OffCampusHire",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeneralRegular.className}>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
